In [205]:
import pandas as pd
import os


data = pd.read_csv("titanic/titanic3.csv")
data.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [215]:
import numpy as np
np.random.random()

0.9361034760604834

In [240]:
def mifuncion (n, a, b):
    x = []
    n = range(n)
    for i in n:
        x.append(np.random.randint(a,b))
    return x
x = mifuncion(100,20,50)

In [244]:
a = np.arange(100)
np.random.shuffle(a)
a

array([91, 69, 76, 25, 28, 78, 26,  5, 86,  8, 20, 64, 93, 51, 48,  3, 27,
       83, 14, 84, 18, 63, 45, 13, 94, 35, 24, 21, 68, 52, 92, 96, 65, 30,
       73, 38, 49, 74, 72, 32, 66, 19, 55,  9, 41, 10, 16, 70, 37, 59, 43,
       95, 40, 98, 58, 15, 60, 11, 61,  7, 22, 90, 99,  0, 67, 71, 77, 80,
       46, 56, 36, 87, 31, 12,  1, 62, 44, 23, 75, 82, 29, 57, 17, 97, 79,
        2, 53, 33, 50, 85,  6, 39,  4, 89, 88, 81, 34, 42, 47, 54])

In [271]:
np.random.random()

0.20724287813818676

In [272]:
np.random.random()

0.05146720330082988

In [212]:
pd.isnull(data["body"]).values

array([ True,  True,  True, ..., False,  True,  True])

In [203]:
data["body"].isna().values

array([ True,  True,  True, ..., False,  True,  True])

In [201]:
data2 = data
data2 = data2.dropna(axis=0, how="all")

In [202]:
data2.head()


pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON